
services:
  postgres:
    image: postgres
    restart: unless-stopped
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "5555:5555"
    volumes:
      - ./.env:/go/src/gitlab.com/trencetech/mypipe-api/bin/mypipe

volumes:
  pgdata:
    driver: local