services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    hostname: api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "5555:5555"
    volumes:
      - ./.env:/go/src/gitlab.com/trencetech/mypipe-api/bin/mypipe