services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "narhzih:dev"
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      APP_ENV: "dev"
    env_file:
      - .env