CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    username VARCHAR(15) NOT NULL UNIQUE,
    twitter_handler VARCHAR(205) DEFAULT NULL UNIQUE,
    email VARCHAR(100) DEFAULT NULL UNIQUE 
);