CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    username VARCHAR(15) NOT NULL UNIQUE,
    profile_name VARCHAR(205) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL UNIQUE,
    cover_photo VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);